[book]
title = "Study: 이것이 자바다"
authors = ["jerok-kim"]
description = "<이것이 자바다> 책을 공부하면서 기록한 정리 글입니다."
language = "kr"
multilingual = true
src = "src"

[rust]
edition = "2021"

[build]
# github pages에서 main브랜치의 docs폴더를 deploy 하기 위해 변경
build-dir = "docs"
create-missing = true
use-default-preprocessors = true
extra-watch-dirs = []

[output.html]
default-theme = "Ayu"
git-repository-url = "https://github.com/jerok-kim/this_is_java"
git-repository-icon = "fa-github"